import { Client, Project, TimesheetEntry, CostCenter, User, DashboardMetrics } from '@/types';

export const mockCostCenters: CostCenter[] = [
  { id: '1', code: 'CC-001', name: 'Residential Installation', description: 'New home electrical installations' },
  { id: '2', code: 'CC-002', name: 'Commercial Wiring', description: 'Commercial building electrical work' },
  { id: '3', code: 'CC-003', name: 'Maintenance & Repair', description: 'Ongoing maintenance and repairs' },
  { id: '4', code: 'CC-004', name: 'Emergency Service', description: 'Emergency callout services' },
  { id: '5', code: 'CC-005', name: 'Panel Upgrades', description: 'Electrical panel upgrades' },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Sunrise Properties',
    contactName: 'John Smith',
    email: 'john@sunriseprops.com',
    phone: '(555) 123-4567',
    address: '123 Main St',
    location: 'Downtown',
    lastContact: '2024-01-15',
    totalHours: 245,
    activeProjects: 3,
    status: 'active',
  },
  {
    id: '2',
    name: 'Metro Construction',
    contactName: 'Sarah Johnson',
    email: 'sarah@metroconst.com',
    phone: '(555) 234-5678',
    address: '456 Oak Ave',
    location: 'Industrial Zone',
    lastContact: '2024-01-18',
    totalHours: 180,
    activeProjects: 2,
    status: 'active',
  },
  {
    id: '3',
    name: 'Riverside Apartments',
    contactName: 'Mike Davis',
    email: 'mike@riverside.com',
    phone: '(555) 345-6789',
    address: '789 River Rd',
    location: 'Riverside',
    lastContact: '2024-01-10',
    totalHours: 320,
    activeProjects: 1,
    status: 'active',
  },
  {
    id: '4',
    name: 'Tech Park Development',
    contactName: 'Emily Brown',
    email: 'emily@techpark.com',
    phone: '(555) 456-7890',
    address: '321 Tech Blvd',
    location: 'Tech District',
    lastContact: '2024-01-20',
    totalHours: 156,
    activeProjects: 4,
    status: 'active',
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    code: 'PRJ-2024-001',
    name: 'Office Building Rewire',
    clientId: '1',
    clientName: 'Sunrise Properties',
    status: 'in-progress',
    budget: 45000,
    actualCost: 28500,
    hoursLogged: 142,
    costCenters: ['1', '2'],
    startDate: '2024-01-05',
    description: 'Complete rewiring of 3-story office building',
    files: [],
  },
  {
    id: '2',
    code: 'PRJ-2024-002',
    name: 'Warehouse Panel Upgrade',
    clientId: '2',
    clientName: 'Metro Construction',
    status: 'quoted',
    budget: 22000,
    actualCost: 0,
    hoursLogged: 0,
    costCenters: ['5'],
    startDate: '2024-01-22',
    description: 'Upgrade main electrical panel to 400A',
    files: [],
  },
  {
    id: '3',
    code: 'PRJ-2024-003',
    name: 'Apartment Complex Maintenance',
    clientId: '3',
    clientName: 'Riverside Apartments',
    status: 'completed',
    budget: 18000,
    actualCost: 17200,
    hoursLogged: 86,
    costCenters: ['3'],
    startDate: '2023-12-01',
    endDate: '2024-01-15',
    description: 'Monthly maintenance contract',
    files: [],
  },
  {
    id: '4',
    code: 'PRJ-2024-004',
    name: 'Data Center Electrical',
    clientId: '4',
    clientName: 'Tech Park Development',
    status: 'in-progress',
    budget: 85000,
    actualCost: 45200,
    hoursLogged: 226,
    costCenters: ['2', '5'],
    startDate: '2023-11-15',
    description: 'New data center electrical infrastructure',
    files: [],
  },
  {
    id: '5',
    code: 'PRJ-2024-005',
    name: 'Residential Solar Integration',
    clientId: '1',
    clientName: 'Sunrise Properties',
    status: 'invoiced',
    budget: 32000,
    actualCost: 31800,
    hoursLogged: 159,
    costCenters: ['1'],
    startDate: '2023-12-10',
    endDate: '2024-01-10',
    description: 'Solar panel electrical integration',
    files: [],
  },
];

export const mockTimesheetEntries: TimesheetEntry[] = [
  {
    id: '1',
    projectId: '1',
    projectName: 'Office Building Rewire',
    clientName: 'Sunrise Properties',
    userId: '1',
    userName: 'Mike Thompson',
    date: '2024-01-20',
    hours: 8,
    activityType: 'installation',
    costCenter: 'CC-001',
    notes: 'Completed wiring for 2nd floor offices',
    photos: [],
    synced: true,
  },
  {
    id: '2',
    projectId: '1',
    projectName: 'Office Building Rewire',
    clientName: 'Sunrise Properties',
    userId: '2',
    userName: 'Dave Wilson',
    date: '2024-01-20',
    hours: 7.5,
    activityType: 'installation',
    costCenter: 'CC-002',
    notes: 'Panel installation in main electrical room',
    photos: [],
    synced: true,
  },
  {
    id: '3',
    projectId: '4',
    projectName: 'Data Center Electrical',
    clientName: 'Tech Park Development',
    userId: '1',
    userName: 'Mike Thompson',
    date: '2024-01-19',
    hours: 10,
    activityType: 'installation',
    costCenter: 'CC-002',
    notes: 'Conduit runs for server racks',
    photos: [],
    synced: true,
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Mike Thompson',
    email: 'mike@company.com',
    role: 'technician',
  },
  {
    id: '2',
    name: 'Dave Wilson',
    email: 'dave@company.com',
    role: 'technician',
  },
  {
    id: '3',
    name: 'Alex Manager',
    email: 'alex@company.com',
    role: 'manager',
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalProjects: 12,
  activeProjects: 5,
  totalHours: 1247,
  totalRevenue: 287500,
  projectsTrend: 8.3,
  hoursTrend: 12.5,
  revenueTrend: 15.2,
  recentActivity: [
    { date: '2024-01-15', hours: 45 },
    { date: '2024-01-16', hours: 52 },
    { date: '2024-01-17', hours: 48 },
    { date: '2024-01-18', hours: 61 },
    { date: '2024-01-19', hours: 55 },
    { date: '2024-01-20', hours: 68 },
    { date: '2024-01-21', hours: 42 },
  ],
};
